name: game_on
description: "GameOn is a Flutter app that connects Minecraft players to their favorite servers, enabling player statistics tracking, economy management, chat integration, and real-time server information from anywhere."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  equatable: ^2.0.5
  freezed: ^2.5.7
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.2.3
  dio: ^5.5.0+1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_analytics: ^11.2.1
  firebase_remote_config: ^5.0.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  either_dart: ^1.0.0
  responsive_sizer: ^3.3.1
  text_scroll: ^0.2.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  web_socket_channel: ^3.0.1
  intl: ^0.19.0
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/logo/
    - images/icons/
    - images/minecraft/

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/lexend/Lexend-Bold.ttf
          weight: 800
        - asset: fonts/lexend/Lexend-SemiBold.ttf
          weight: 700
        - asset: fonts/lexend/Lexend-Medium.ttf
          weight: 600
        - asset: fonts/lexend/Lexend-Regular.ttf
          weight: 500
        - asset: fonts/lexend/Lexend-Light.ttf
          weight: 400
        - asset: fonts/lexend/Lexend-ExtraLight.ttf
          weight: 300
