// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNOW7jU7itI73taYkEmimb_OQb7KvyITo',
    appId: '1:893923538067:web:fb89e5ba0db3f1bfa04966',
    messagingSenderId: '893923538067',
    projectId: 'gameon-86551',
    authDomain: 'gameon-86551.firebaseapp.com',
    storageBucket: 'gameon-86551.appspot.com',
    measurementId: 'G-XJXQ80ZF35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKY79L5SBQb3bwQj7geJ53abSLNQsgU2k',
    appId: '1:893923538067:android:05eba6e6651baa2aa04966',
    messagingSenderId: '893923538067',
    projectId: 'gameon-86551',
    storageBucket: 'gameon-86551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ5GNsH3lCwJLPruPwNKRoFMIhpFm4wME',
    appId: '1:893923538067:ios:f0a4f1c06f65bcd2a04966',
    messagingSenderId: '893923538067',
    projectId: 'gameon-86551',
    storageBucket: 'gameon-86551.appspot.com',
    iosBundleId: 'com.gameon.gameOn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ5GNsH3lCwJLPruPwNKRoFMIhpFm4wME',
    appId: '1:893923538067:ios:f0a4f1c06f65bcd2a04966',
    messagingSenderId: '893923538067',
    projectId: 'gameon-86551',
    storageBucket: 'gameon-86551.appspot.com',
    iosBundleId: 'com.gameon.gameOn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNOW7jU7itI73taYkEmimb_OQb7KvyITo',
    appId: '1:893923538067:web:ef9508e11d65c805a04966',
    messagingSenderId: '893923538067',
    projectId: 'gameon-86551',
    authDomain: 'gameon-86551.firebaseapp.com',
    storageBucket: 'gameon-86551.appspot.com',
    measurementId: 'G-FE4TX48E9S',
  );
}
