name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    # Uncomment the following step to verify the use of 'flutter format' on each commit.  
    # - name: Verify formatting
    #   run: flutter format --output=none --set-exit-if-changed .
      
    - name: Analyze project source
      run: flutter analyze